project:
  type: website
  output-dir: docs


website:
  title: "Society of Cutaneous Oncology Journal Club"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: theme.scss
#      - cosmo
#      - brand
#    css: styles.css
    toc: true



