project:
  type: website
  output-dir: docs


website:
  title: "April 10th 2025 - Ipi-Nivo for MCC - results from Checkmate 358"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



