project:
  type: website
  output-dir: docs


website:
  title: "Society of Cutaneous Oncology Journal Club"
  navbar:
    right:
      - text: Perspectives on the Science
        href: https://journalofcutaneousoncology.io
        target: _blank
      - text: SoCO JC Timeline 
        href: https://cutaneousoncology.shinyapps.io/soco_journal_club_timeline
        target: _blank
      - text: Pre Journal Club Survey
        href: Pre_JC_Survey.qmd
      - text: Article
        href: article.qmd
      - text: Post Journal Club Survey
        href: Post_JC_Survey.qmd
      

format:
  html:
    theme: theme.scss
#      - cosmo
#      - brand
#    css: styles.css
    toc: true



