project:
  type: website
  output-dir: docs


website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Society of Cutaneous Oncology Journal Club
      - text: Perspectives on the Science
        href: https://journalofcutaneousoncology.io
        target: _blank
      - text: SoCO JC Timeline 
        href: https://cutaneousoncology.shinyapps.io/soco_journal_club_timeline
        target: _blank
      

format:
  html:
    theme: theme.scss
#      - cosmo
#      - brand
#    css: styles.css
    toc: true



